# Generated by Django 2.2.2 on 2019-07-28 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Story',
            fields=[
                ('story_id', models.AutoField(primary_key=True, serialize=False)),
                ('group_name', models.CharField(max_length=50)),
                ('sen_1', models.CharField(max_length=200)),
                ('sen_2', models.CharField(max_length=200)),
                ('sen_3', models.CharField(max_length=200)),
                ('sen_4', models.CharField(max_length=200)),
                ('sne_5', models.CharField(max_length=200)),
                ('Q1', models.CharField(max_length=200)),
                ('Q2', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
